
repos:
-   repo: local
    hooks:
    - id: rye-lint
      name: rye-lint
      description: "Lint Python via 'rye lint'"
      entry: rye lint --fix
      language: system
      types_or: [python, pyi]
      args: []
      require_serial: true
      additional_dependencies: []
      minimum_pre_commit_version: "2.9.2"
    - id: rye-format
      name: rye-format
      description: "Format Python via 'rye fmt'"
      entry: rye fmt
      language: system
      types_or: [python, pyi]
      args: []
      require_serial: true
      additional_dependencies: []
      minimum_pre_commit_version: "2.9.2"
    - id: rye-test
      name: rye-test
      description: "Test Python via 'rye test'"
      entry: rye test
      language: system
      types_or: [python, pyi]
      args: []
      pass_filenames: false
      require_serial: true
      additional_dependencies: []
      minimum_pre_commit_version: "2.9.2"
-   repo: local
    hooks:
      - id: mypy-src
        name: mypy-src
        language: system
        entry: rye run mypy 
        files: src
      - id: mypy-tests
        name: mypy-tests
        language: system
        entry: rye run mypy --ignore-missing-imports
        files: tests 