name: Basic CI (mirror of local pre-commit CI)

on: [push, pull_request]

jobs:
  basic-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64' # GH does not support arm64, i.e. modern Mac, only x64
      - name: Setup rye on runner
        shell: bash
        run: curl -sSf https://rye.astral.sh/get | bash
      - name: Install rye dependencies
        run: rye sync
      - name: Run precommit CI hooks
        run: rye run pre-commit run --all-files