name: Basic CI

on: [push, pull_request]

jobs:
  basic-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64' # GH does not support arm64, i.e. modern Mac, only x64
      - name: Setup rye
        uses: eifinger/setup-rye@v2
      - name: Install original package
        run: rye sync
      - name: run precommit hooks
        run: pre-commit run --all-files